[package]
name = "mgba_log"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.18"
voladdress = "1.3.0"

[dev-dependencies]
cargo_metadata = "0.15.4"
mgba_logs = {path = "tests/mgba_logs"}
serde_json = "1.0.96"
